import { AppInfo, Task, appendLog, nowISO, store } from './store.js';

export function seed() {
  const apps: AppInfo[] = [
    {
      appId: 'app-001',
      appName: '用户中心',
      appDescription: '负责用户登录、注册、账号管理',
      gitUrl: 'git@gitlab.example.com:demo/user-center.git',
      defaultBranch: 'master',
      aiwxPipelineId: 'pipeline-001',
      aiwxEnvLimit: 5,
    },
    {
      appId: 'app-002',
      appName: '订单服务',
      appDescription: '订单创建、支付、退款',
      gitUrl: 'git@gitlab.example.com:demo/order-service.git',
      defaultBranch: 'main',
      aiwxPipelineId: 'pipeline-002',
      aiwxEnvLimit: 3,
    },
    {
      appId: 'app-003',
      appName: '消息推送',
      appDescription: '站内信、Push、短信',
      gitUrl: 'git@gitlab.example.com:demo/notify.git',
      defaultBranch: 'master',
      aiwxPipelineId: 'pipeline-003',
      aiwxEnvLimit: 5,
    },
  ];
  apps.forEach((a) => store.apps.set(a.appId, a));

  const seedTasks: Task[] = [
    {
      id: 'task-005',
      projectId: 'project-002',
      requirementId: 'REQ-20005',
      title: '商品详情页新增拼团模块',
      content: '根据服务端返回的拼团活动信息，在商品详情页展示拼团玩法和倒计时。',
      appId: 'app-002',
      planMode: true,
      status: 'pending_start',
      createdAt: nowISO(),
      updatedAt: nowISO(),
    },
    {
      id: 'task-006',
      projectId: 'project-003',
      requirementId: 'REQ-30012',
      title: '支持发送微信订阅消息',
      content: '消息中心需接入微信订阅消息接口，支持用户在小程序内订阅并接收通知。',
      appId: 'app-003',
      planMode: false,
      status: 'pending_start',
      createdAt: nowISO(),
      updatedAt: nowISO(),
    },
    {
      id: 'task-007',
      projectId: 'project-001',
      requirementId: 'REQ-10101',
      title: '用户密码复杂度校验升级',
      content: '注册和修改密码时，要求密码长度不少于8位，且包含大小写字母和数字。',
      appId: 'app-001',
      planMode: true,
      status: 'pending_start',
      createdAt: nowISO(),
      updatedAt: nowISO(),
    },
    {
      id: 'task-008',
      projectId: 'project-002',
      requirementId: 'REQ-20222',
      title: '订单取消增加二次确认弹窗',
      content: '在订单列表和详情页点击取消订单时，弹出对话框提示用户确认，避免误触。',
      appId: 'app-002',
      planMode: false,
      status: 'pending_start',
      createdAt: nowISO(),
      updatedAt: nowISO(),
    },
    {
      id: 'task-001',
      projectId: 'project-001',
      requirementId: 'REQ-10086',
      title: '优化登录页错误提示',
      content: '用户登录失败时需要展示明确的错误原因，区分密码错误、账号不存在、网络异常。',
      appId: 'app-001',
      planMode: true,
      status: 'queued',
      createdAt: nowISO(),
      updatedAt: nowISO(),
    },
    {
      id: 'task-002',
      projectId: 'project-001',
      requirementId: 'REQ-10087',
      title: '订单详情页增加退款入口',
      content: '在订单详情页根据订单状态展示"申请退款"按钮，已退款订单展示退款进度。',
      appId: 'app-002',
      planMode: false,
      status: 'queued',
      createdAt: nowISO(),
      updatedAt: nowISO(),
    },
    {
      id: 'task-003',
      projectId: 'project-002',
      requirementId: 'REQ-20001',
      title: '推送消息支持富文本',
      content: '允许推送消息包含粗体、链接、表情，按平台能力降级渲染。',
      appId: 'app-003',
      planMode: true,
      status: 'queued',
      createdAt: nowISO(),
      updatedAt: nowISO(),
    },
    {
      id: 'task-004',
      projectId: 'project-001',
      requirementId: 'REQ-10000',
      title: '历史需求：修复手机号校验正则',
      content: '修复手机号校验不支持 167 号段的问题。',
      appId: 'app-001',
      planMode: false,
      status: 'completed',
      baseBranch: 'master',
      baseCommit: 'a1b2c3d4',
      branchName: 'aiwx/feat-REQ-10000',
      sandboxId: 'sb-project-001',
      mrUrl: 'https://gitlab.example.com/demo/user-center/-/merge_requests/42',
      createdAt: nowISO(),
      updatedAt: nowISO(),
    },
  ];
  seedTasks.forEach((t) => {
    store.tasks.set(t.id, t);
    appendLog({
      taskId: t.id,
      action: 'task:created',
      actor: 'system',
      status: 'info',
      message: `任务 ${t.id} 已进入队列`,
    });
  });
}
